### ISSUE TITLE
[Feature-request] improve the project creation process

### ISSUE THREAD

**Issue by rpkoller** [ddev/vscode-ddev-manager#12]
**Is your feature request related to a problem? Please describe.**
The steps for setting up a ddev project in vscode-ddev-manager have a few potential stepping stones: 
Step 1: The description for "enter project name" is "sort of" confusing. After you tried it one time it is ok but still, to start instructions with "normally the name of your directory" raises a few question marks in my head. i asked myself what are the other cases that are not normal? and it is also not clear that in step three you set or create and set the project directory.
Step 2: In my case i have set Drupal 10 as the project type. 
Step 3: i then created and set my project directory. 

=> the problem  in the end
![Screenshot 2023-09-23 at 14 10 08](https://github.com/biati-digital/vscode-ddev-manager/assets/1665422/2a893649-92ba-4598-ad43-3b022f22a949)

the docroot is still set to the default root value instead of web necessary for drupal 10. there was no option to set the docroot in the available step

**Describe the solution you'd like**
- One initial idea for the `Enter project name` description might be:  `Set the name for your project in DDEV. In one of the next steps you will select a folder for the project.` That way you state that the user is entering the name a project is referenced in DDEV and also notify the user that in one of the next steps you will select the folder the project is stored within the file system. That way the description would be a bit more clear and informative and some potential uncertainties are removed. 
- Add the step for setting the docroot like in `ddev config` right after setting the project name.

**Comment by biati-digital** [comment]
Hi @rpkoller Yes, this part it's still in progress as I needed to focus first on other functionalities but I want to improve this process.

1.- I see how that description can be confusing, I took that text directly from the docs when I was doing some testing and never changed it. Definitely will be updated to make it more clear.

2.- I'm not sure about adding another step, what I wanted to do is to set some defaults, for example, if the project is Drupal set the docroot and maybe other specific settings for Drupal, the same for Typo3, WordPress, etc. (Following the the [DDEV docs](https://ddev.readthedocs.io/en/stable/users/quickstart/)) 

At the end I want the creation process to be quick and simple.

**Comment by biati-digital** [comment]
There's a new update 1.3.2 that includes the change in the description and also some default configuration depending on the project type. Please try it and let me know what you think.

**Comment by rpkoller** [comment]
sorry for the delayed answer. I've tested that latest version now. one observation and one comment. 

about the first step. with the updated description it is way more clear from my perspective thanks for that. but i'Ve noticed one detail. if you leave the project name empty and just press enter you are able to proceed to the next step selecting the project type. and if you select one and then create and select a folder that folder wont contain the ddev project settings folder. i think the extension should intervene if the project name is left empty in the first step. 

about the docroot i understand your point and i can confirm that at least for drupal where i have tested, the docroot is properly set to web for a drupal10 project type. but i am still not sure if due to that convenience step at least for new users the docroot setting is left unnoticed in the config.yaml and then lead into some troubles down the road? in particular for php projects you are unable to predict what the docroot will be. 
one idea for ddev AND the vscode-ddev-manager might be to  have all three steps for both. but i would switch the order: 

1. project name  (the default in ddev is the name of the folder the ddev config command is run in) 
2. project type
3. docroot (based on the project type provide a potential default value so in most cases the user has just to press return to confirm the default value. but that way you make sure the user is aware that the docroot has to be set and or could be set, as well as provide the convenience of having the correct docroot value for most project types as the default value.)

**Comment by rpkoller** [comment]
1. thank you! 
2. oh wow i really like the idea in general! instead of having a wizardy stepwise process having a single screen for all the available settings prefilled with the default values for the chosen project type, that would definitely provide some additional value in comparison to the command line approach in ddev. the only tricky detail i see for example for project type that have more than one instance like drupal which has currently 5 (drupal 6-10) soon 6 (drupal 11) different ones . should each be listed in the sidebar or have a select list on top of the drupal project type where the user is able to select the specific version? cuz based on the project type the default values differ significantly within drupal for example. but again the idea of having a single view for setting up a project instead of the stepwise process i like a lot!

**Comment by biati-digital** [comment]
In those cases the sidebar would only display Drupal, the form on the right would display an option (select field) so the user can select the version (drupal 6-10) changing that would basically do the same as the sidebar, get the defaults and pre-fill the form.

I'm really glad you like the idea.

**Comment by biati-digital** [comment]
The name bug was fixed in the latest version, I'll close this issue now. I'll investigate more about the UI and I'll be sharing the progress.

**Comment by rpkoller** [comment]
just tested with the latest version and i can confirm the issue with the empty project name is properly fixed. thanks a lot!
