### ISSUE TITLE
[Feature-request] Open project in VScode

### ISSUE THREAD

**Issue by tyler36** [ddev/vscode-ddev-manager#16]
**Is your feature request related to a problem? Please describe.**
I can manage any DDEV project from my current workspace which is great.
However, sometimes, I want to quickly jump over and alter a file or update a dependency.

**Describe the solution you'd like**
It would be convienient if there were 2 additional options:
- Open project in current window
- Open project in new widow

This would allow DDEV Manage to also act like a project manager.
I could quickly spawn a new VScode instance and view logs files etc.
Or if, I want to switch context, open the selected project in my current window, replacing it entirely.

![image](https://github.com/ddev/vscode-ddev-manager/assets/7234392/5ad6dc7c-e94a-44d0-839d-72a024339c92)

**Describe alternatives you've considered**
I use to use https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager to perform the describe behaviour. 
It's good for bouncing between projects but does not have "DDEV management".

I understand that this may be outside the scope of this extension.

**Comment by biati-digital** [comment]
Hi, yes I was thinking on doing something like this but using the command palette to replace extensions like `project manager` I think adding options in the tree view can also help.

I'll probably pospone this until next year, I'm currently having a lot of work so I need to focus on that so i can have some free time and some rest on December.

**Comment by tyler36** [comment]
Thank you for the update and consideration. 😄

**Comment by biati-digital** [comment]
This has been added in the latest update. There's two new options in the project menu in the sidebar to open the project in the current window or a new window.

if you prefer, you can also use the command palette, there's two new commands (you can assign a keyboard shortcut) the first one "List DDEV Projects to Open in Editor" will display a list of DDEV projects, pressing enter will open the selected project in the active editor, you can see that each project item in the list has a button (you need to use the mouse) If you click it it will open the project in a new window.

The other command is the same but will always open the projects in a new window "List DDEV Projects to Open in New Editor Window" I usually always open projects in a new window so you can choose your favorite method.

This update has a lot of [new things](https://github.com/ddev/vscode-ddev-manager/blob/main/CHANGELOG.md) so please try it and let me know if you find a bug or something it's not working correctly.

**Comment by tyler36** [comment]
Confirmed on `2.0.1`. Works great!

![image](https://github.com/ddev/vscode-ddev-manager/assets/7234392/a4dda8c2-05a5-4811-b595-879ac88b826a)

Thank you. I'll close this ticket as "completed".
