### ISSUE TITLE
[BUG] Wrong database name when opening Sequel Ace with "Open Database Administration"

### ISSUE THREAD

**Issue by inf0dr0id** [ddev/vscode-ddev-manager#17]
**Describe the bug**
When opening Sequel Ace with the 'DDEV: Open Database Administration' command the project name is used as the database name but the default DDEV database name is `db` which yields an `Unknown database` error.

`ddev sequelace` does the following:
`open mysql://root:root@xyz.ddev.site:32782/db -a '/Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace'`

**To Reproduce**

1. "ddevManager.defaultDatabaseManager": "Sequel Ace"
2. Click on 'Open Database Administration'
3. See error

**Expected behavior**
Sequel Ace should be opened with database `db` by default or this should be configurable.

**Screenshots**

With 'DDEV: Open Database Administration'
<img width="355" alt="Bildschirmfoto 2023-11-29 um 11 26 07" src="https://github.com/ddev/vscode-ddev-manager/assets/24397146/d9f0a1ae-c590-4d29-bafa-9230868c8aff">

With `ddev sequelace`
<img width="337" alt="Bildschirmfoto 2023-11-29 um 11 26 34" src="https://github.com/ddev/vscode-ddev-manager/assets/24397146/d409187a-2dd9-41d7-9b90-e567f5445285">

**System:**

- OS: macOS 14.1.1
- DDEV version: v1.22.5
- Docker provider: Orbstack
- VSCode version: 1.84.2
- DDEV Manager version: v1.4.0

**Comment by biati-digital** [comment]
Hi. This is not related to this extension, the extension only runs DDEV commands, in this case ddev sequelpro it does not pass database names or any other configuration.

Please post the issue directly in the ddev repo.

**Comment by inf0dr0id** [comment]
Thanks for your reply but in the VSCode output console for DDEV I can see this when using 'Open Database Administration':

2023-11-30 08:17:02.731 [info] + open mysql://root:root@project_name.ddev.site:32791/**project_name** -a '/Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace'

This happens with the following ddev commands in a terminal with the project folder as the current directory:

\> ddev sequelace
\+ open mysql://root:root@project_name.ddev.site:32791/**db** -a '/Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace'

\> ddev sequelace **project_name**
\+ open mysql://root:root@project_name.ddev.site:32791/**project_name** -a '/Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace'

Are you sure you're not adding the project name when calling `ddev sequelace`?

If not and this is a problem with ddev I would be glad to post an issue in the ddev repo but I'm not entirely sure what the bug description would be.

**Comment by biati-digital** [comment]
Ohh, i see what you mean, everything related to the database was moved to a new class to handle phpMyAdmin, Adminer and maybe some VS Code db extensions, in that new class the project name is added exacly as you mention. 

I use Tableplus and never noticed this issue, checking the command's code, seems that the Tableplus command has the db name directly in the code (ignoring args) and the sequelace command uses the first arg (if provided) as database name.

I'll remove the project name from the command and publish an update this week.

Thank's for checking this.

**Comment by biati-digital** [comment]
Hi. An update has been published (1.4.2) please try it and let me know if it's working

**Comment by inf0dr0id** [comment]
It's working now. Thank you.

**Comment by biati-digital** [comment]
Glad to hear it's working correctly.
