### ISSUE TITLE
Wrong version detected

### ISSUE THREAD

**Issue by morvy** [ddev/vscode-ddev-manager#20]
Hi,
on every launch of VSC I get a popup about updating ddev from 1.22.6 to latest 1.23 but I'm already on latest ddev.
I have Win11 + WSL2.
Where does the extension take version from?

**Comment by stasadev** [comment]
Hi @morvy,

You may have multiple versions of DDEV installed and the `$PATH` is being read differently from your console and VSCode.

You need to remove DDEV v1.22.6:
https://ddev.readthedocs.io/en/stable/users/usage/faq/#why-do-i-have-an-old-ddev

**Comment by morvy** [comment]
You're right .. I forgot I had to update windows installer too because of gsudo, so this was 1.22.6 while WSL2 ddev was 1.23.2
