### ISSUE TITLE
[BUG] The DB service is marked `undefined` when the database is Postgres

### ISSUE THREAD

**Issue by detygon** [ddev/vscode-ddev-manager#21]
**Describe the bug**
The DB service is marked `undefined` when the configured database for the project is Postgres. However it does show the version.

**To Reproduce**

1. Show the details of a DDEV project with Postgres as the DB

**Expected behavior**
The correct service is shown.

**Screenshots**
<img width="253" alt="image" src="https://github.com/ddev/vscode-ddev-manager/assets/25983025/22c39f69-0e7d-4cce-8238-ea1026180ba2">

**System (please complete the following information):**

- OS: macOS Sonoma
- DDEV version: v1.23.2
- Docker provider: Orbstack
- VSCode version: 1.90.1
- DDEV Manager version: v2.5.1

**Comment by biati-digital** [comment]
Hi @detygon. I've confirmed the bug, it will be fixed in the next update.

**Comment by biati-digital** [comment]
This should be fixed in version 2.6.0, please update the extension and let me know if it's working.
