### ISSUE TITLE
ddev: command not found

### ISSUE THREAD

**Issue by erkage** [ddev/vscode-ddev-manager#22]
**Describe the bug**
For some reason I can't manage any ddev project from the extension as it says `ddev is not installed`. But it's installed and it's working from terminal (just copied the version info with the `--version` option).
In the logs I found `/bin/sh: ddev: command not found` error and I think the problem is that it should use `zsh` for the shell - as the terminal - but I couldn't find any configuration for it.
Afaik I haven't changed nor configured anything related to this, it just stopped working.

Any suggestions? Thanks in advance.

**System:**

- OS: macOS Sonoma 14.5
- DDEV version: v1.23.3 (with homebrew)
- Docker provider: Docker Desktop
- VSCode version: 1.91.1
- DDEV Manager version: v2.5.1

**Comment by rfay** [comment]
This means that in the context of the vscode manager, the `ddev` binary cannot be found. The way it *should* be found is with the PATH environment variable. So I imagine that in your terminal, `which ddev` gets you /opt/homebrew/bin/ddev, right? But I imagine that you have something in your terminal that changes your PATH that vscode doesn't see...

Can you say what shell you're using? (zsh, bash, etc?) It looks like the vscode extension is trying to use /bin/sh (bourne shell) to run it, so you may just want to add `export PATH=$PATH:/opt/homebrew/bin` to your ~/.profile
