### ISSUE TITLE
[Feature-request] Add option to start / stop xdebug?

### ISSUE THREAD

**Issue by jcogs-design** [ddev/vscode-ddev-manager#23]
Would be really helpful if an option could be added to this that allowed you to start / stop xdebug (and show you current status of this).

The alternative is to do it manually (`ddev xdebug on` etc) but having this added to the extension would be a nice addition.

Thanks in advance for considering.

**Comment by jcogs-design** [comment]
Hmm.

It is a super-useful extension. Kudos for creating / supporting.

However I guess I must be missing some understanding of how to configure the extension.

If I start a debug session in VSCode xdebug is not enabled on the ddev instance in the workspace I'm using.
If I type `ddev xdebug on` into the terminal for the workspace it does get enabled.

Likewise when I end a debug session, xdebug is not disabled.
If I type `ddev xdebug off` into the terminal for the workspace it does get disabled.

The only other thing that would be good to be able to do is have a button that is equivalent to typing in `ddev sequelace` in the terminal - again it is not clear how this ddev built in function is triggered through the extension - would be really good to know how!

If you have any guidance on how to do these things I'd be most grateful to know.

**Comment by rfay** [comment]
Just a note that if you use the recommended https://ddev.readthedocs.io/en/stable/users/snippets/tasks.json from the docs at https://ddev.readthedocs.io/en/stable/users/debugging-profiling/step-debugging/#visual-studio-code-vs-code-debugging-setup, you don't even need vscode-ddev-manager to be involved, it gets done for you by VS Code.

**Comment by jcogs-design** [comment]
Thanks!
As expected I was definitely missing some understanding ... 
Updating the VS Code settings to auto start / stop Xdebug certainly is an even better option.

**Comment by biati-digital** [comment]
> Just a note that if you use the recommended https://ddev.readthedocs.io/en/stable/users/snippets/tasks.json from the docs at https://ddev.readthedocs.io/en/stable/users/debugging-profiling/step-debugging/#visual-studio-code-vs-code-debugging-setup, you don't even need vscode-ddev-manager to be involved, it gets done for you by VS Code.

The extension creates the taks.json and launch.json automatically.

@jcogs-design Make sure you have enabled in the extension settings "Automatícally Configure Debugger"

**Comment by jcogs-design** [comment]
"Automatically Configure Debugger" was / is enabled, but didn't seem to have made any changes to either launch.json or tasks.json (which were not present on my system until I created them in response to @rfay comment).

**Comment by biati-digital** [comment]
Please consider opening an issue providing all the information you can. Maybe the API was changed in the latest VSCode update.
